package problems

import utils.Utils.time

// https://projecteuler.net/problem=29
// Number of distinct terms in the sequence generated by a^b for (a, b) in [2;100]
object Problem029 {
  def distinctTerms(ubound: Int): Int =
    (for(
      a <- 2 to ubound;
      b <- 2 to ubound
    ) yield BigInt(a).pow(b))
      .distinct.length

  def main(args: Array[String]): Unit =
    println(time(distinctTerms(100)))
}
